### PR TITLE
Unbundle maps from Opal release

### PR DESCRIPTION
**Pull request by webdev778**
image

### CODE REVIEW

**Comment by ronaldtse** [comment]
LGTM, feel free to merge when ready.

**Comment by webdev778** [comment]
- Restructred folder
image

- Enable to load system json file using require as like loading other libraries.
image

**Comment by webdev778** [comment]
ping @strogonoff, the library has been updated, can you publish the changes again?

**Comment by strogonoff** [comment]
@ronaldtse maybe you could change permissions on NPM package to allow interscript-js maintainers to publish it?

https://github.com/interscript/interscript-js#release-process

I don’t think I should be a bottleneck here

**Comment by ronaldtse** [comment]
Added @webdev778 as a package maintainer.

**Pull request merged**
